output_dir: ~/experiments/

dataset:
  class: kinship
  path: ~/datasets/knowledge_graphs/

task:
  class: KnowledgeGraphCompletion
  model:
    class: edgeformer
    num_message_rounds: 8
    dropout: 0.2
    dim: 128
    num_heads: 4
    num_mlp_layer: 2
    remove_one_hop: yes
    max_grad_norm: 1.0
    share_layers: yes
    no_share_layers: no
    lesion_values: no
    lesion_scores: no
    flat_attention: no
    ff_factor: 4
    num_relation: 25
    num_nodes: 104
    target_size: 25
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.5
  sample_weight: no

optimizer:
  class: Adam
  lr: 5.0e-3


engine:
  gpus: {{ gpus }}
  batch_size: 8

train:
  num_epoch: 20

metric: mrr