output_dir: ~/experiments/

dataset:
  class: kinship
  path: ~/datasets/knowledge_graphs/


task:
  class: KnowledgeGraphCompletion
  model:
    class: edgeformer
    num_message_rounds: 8
    dropout: 0.2
    dim: 200
    num_heads: 4
    max_grad_norm: 1.0
    share_layers: True
    no_share_layers: False
    data_path:
    lesion_values: False
    lesion_scores: False
    flat_attention: False
    ff_factor: 4
    num_relation: 26
    target_size: 25

optimizer:
  class: Adam
  lr: 1.0e-3


engine:
  gpus: {{ gpus }}
  batch_size: 400

train:
  num_epoch: 50

metric: mrr